force-app/main/default/objects/MyTime_Settings__c/MyTime_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MyTime Settings</label>
</CustomObject>

force-app/main/default/objects/MyTime_Settings__c/fields/Salary_Day_number_of_day__c.field-meta.xml
<CustomField>
    <fullName>Salary_Day_number_of_day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Salary Day(number of day)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SalaryDetailsScheduler.cls
global class SalaryDetailsScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        MyTime_Settings__c settings = MyTime_Settings__c.getOrgDefaults();
        if (settings == null || settings.Salary_Day_number_of_day__c == null) return;

        Integer scheduledDay = Integer.valueOf(settings.Salary_Day_number_of_day__c);
        Date today = Date.today();

        if (today.day() == scheduledDay) {
            GenerateSalaryDetailsBatch batch = new GenerateSalaryDetailsBatch();
            Database.executeBatch(batch, 200);
        }
    }
}