force-app/main/default/objects/External_User__c/External_User__c.object-meta.xml
<CustomObject>
    <label>External User</label>
    <nameField>
        <label>External User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salary_Detail__c/Salary_Detail__c.object-meta.xml
<CustomObject>
    <label>Salary Detail</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Salary Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salary Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Salary_Detail__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <label>Compensation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Salary_Detail__c/fields/External_User__c.field-meta.xml
<CustomField>
    <fullName>External_User__c</fullName>
    <label>External User</label>
    <referenceTo>External_User__c</referenceTo>
    <relationshipLabel>Salary Details</relationshipLabel>
    <relationshipName>Salary_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Salary_Detail__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <formula>Amount__c  +  Compensation__c  -  Tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SalaryDetailController.cls
public without sharing class SalaryDetailController {
   

    @AuraEnabled(cacheable=true)
    public static List<Salary_Detail__c> getAllSalaryDetails(Id userId) {
        return [
            SELECT Id, Date__c, Rate__c, Compensation__c, Hours__c, Tax__c, Final__c
            FROM Salary_Detail__c
            WHERE External_User__c = :userId
            ORDER BY Date__c DESC
        ];
    }

}