force-app/main/default/objects/External_User__c/External_User__c.object-meta.xml
<CustomObject>
    <label>External User</label>
    <nameField>
        <label>External User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_User__c/fields/IsHR__c.field-meta.xml
<CustomField>
    <fullName>IsHR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsHR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/IsManager__c.field-meta.xml
<CustomField>
    <fullName>IsManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsManager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/MyTime_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MyTime Settings</label>
</CustomObject>

force-app/main/default/objects/MyTime_Settings__c/fields/Allowed_Domains__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Domains__c</fullName>
    <label>Allowed Domains</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/fields/Days_Off__c.field-meta.xml
<CustomField>
    <fullName>Days_Off__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Days Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/fields/Hours_per_week__c.field-meta.xml
<CustomField>
    <fullName>Hours_per_week__c</fullName>
    <defaultValue>40</defaultValue>
    <label>Hours per week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/fields/Illnesses__c.field-meta.xml
<CustomField>
    <fullName>Illnesses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Illnesses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/fields/Salary_Day_number_of_day__c.field-meta.xml
<CustomField>
    <fullName>Salary_Day_number_of_day__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Salary Day(number of day)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/fields/Taxes__c.field-meta.xml
<CustomField>
    <fullName>Taxes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Taxes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MyTime_Settings__c/fields/Vacancies__c.field-meta.xml
<CustomField>
    <fullName>Vacancies__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vacancies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoginControllerTest.cls
@isTest
private class LoginControllerTest {

    private static External_User__c createTestUser() {
        MyTime_Settings__c settings = new MyTime_Settings__c(
            Days_Off__c = 10,
            Hours_per_week__c = 40,
            Illnesses__c = 5,
            Salary_Day_number_of_day__c = 15,
            Taxes__c = 20,
            Vacancies__c = 3,
            Budget__c = 90,
            Allowed_Domains__c = 'example.com'
        );
        insert settings;
        // Create External_User__c records
        External_User__c user1 = new External_User__c(
            Name = 'Test User 1',
            Email__c = 'testuser1@example.com',
            IsManager__c = false,
            IsHR__c = false,
            Role__c = 'Developer'
        );
        insert user1;
        return user1;
    }
    
     private static External_User__c createTestUserHR() {
        MyTime_Settings__c settings = new MyTime_Settings__c(
            Days_Off__c = 10,
            Hours_per_week__c = 40,
            Illnesses__c = 5,
            Salary_Day_number_of_day__c = 15,
            Taxes__c = 20,
            Vacancies__c = 3,
            Budget__c = 90,
            Allowed_Domains__c = 'example.com'
        );
        insert settings;
        // Create External_User__c records
        External_User__c user1 = new External_User__c(
            Name = 'Test User 1',
            Email__c = 'testuser1@example.com',
            IsManager__c = false,
            IsHR__c = true,
            Role__c = 'Developer'
        );
        insert user1;
        return user1;
    }
    private static External_User__c createTestUserManager() {
      
        // Create External_User__c records
        External_User__c user1 = new External_User__c(
            Name = 'Test User 2',
            Email__c = 'testuser2@example.com',
            IsManager__c = true,
            IsHR__c = false,
            Role__c = 'Developer'
        );
        insert user1;
        return user1;
    }

    @isTest
    static void testLoginUser() {
        // Arrange
        External_User__c user = createTestUser();

        Test.startTest();
        String token = LoginController.loginUser(user.Email__c, 'fakePassword');
        GoogleLoginController.createAuthURL();
        Utils.getNamespacePrefix();
        Test.stopTest();
        
        

        System.assertNotEquals(null, token, 'Token should not be null');
        System.assertEquals(
            EncodingUtil.base64Encode(Blob.valueOf(user.Id)),
            token,
            'Token should match encoded user Id'
        );
    }

    @isTest
    static void testValidateSession_validToken() {
        // Arrange
        External_User__c user = createTestUser();
        String token = LoginController.generateSessionToken(user);

        // Act
        Test.startTest();
        External_User__c validatedUser = LoginController.validateSession(EncodingUtil.urlEncode(token, 'UTF-8'));
        Test.stopTest();

        // Assert
        System.assertNotEquals(null, validatedUser, 'Validated user should not be null');
        System.assertEquals(user.Id, validatedUser.Id, 'Validated user ID should match original');
    }



    @isTest
    static void testGenerateSessionToken() {
        External_User__c user = createTestUser();
        String token = LoginController.generateSessionToken(user);

        System.assertEquals(EncodingUtil.base64Encode(Blob.valueOf(user.Id)), token, 'Token should match expected encoding');
        delete user;
    }
    
    @isTest
    static void testUsers() {
        External_User__c user = createTestUserHR();
        External_User__c user2 = createTestUserManager();

        delete user;
        delete user2;
    }
       @isTest
    static void testUsersUpdate() {
        External_User__c user = createTestUserHR();
        External_User__c user2 = createTestUserManager();
		user.IsHR__c = false;
        user2.IsManager__c = false;
        update user;
        update user2;
    }
}