force-app/main/default/objects/External_User__c/External_User__c.object-meta.xml
<CustomObject>
    <label>External User</label>
    <nameField>
        <label>External User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report__c/Report__c.object-meta.xml
<CustomObject>
    <label>Report</label>
    <nameField>
        <displayFormat>Report-{000000}</displayFormat>
        <label>Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Report__c/fields/External_User__c.field-meta.xml
<CustomField>
    <fullName>External_User__c</fullName>
    <label>External User</label>
    <referenceTo>External_User__c</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Report__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report__c/fields/IsApproved__c.field-meta.xml
<CustomField>
    <fullName>IsApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsApproved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Report__c/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <label>Minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Reports</relationshipLabel>
    <relationshipName>Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report__c/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <label>TaskType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReportController.cls
public without sharing class ReportController {

    @AuraEnabled
    public static List<Report__c> getReportsByDate(String dateISO, Id userId) {
    Date reportDate = Date.valueOf(dateISO);
    return [SELECT Id, Name, Project__c, Project__r.Name,TaskType__c, Description__c, Hours__c, Minutes__c, CreatedDate, LastModifiedDate, isApproved__c, Date__c
            FROM Report__c
            WHERE Date__c = :reportDate AND External_User__c = :userId];
    }

    @AuraEnabled
    public static List<Report__c> getReportsByDatePeriod(Id userId, Date fromDate, Date toDate) {

    return [SELECT Id, Name, Project__c, Project__r.Name,TaskType__c, Description__c, Hours__c, Minutes__c, CreatedDate, LastModifiedDate, isApproved__c, Date__c, External_User__c
            FROM Report__c
            WHERE Date__c <= :toDate AND Date__c>=:fromDate AND External_User__c = :userId and Project__r.Name!='Social package'];
    }


    @AuraEnabled
    public static List<Report__c> getSocialPackageReportsByDatePeriod(Id userId, Date fromDate, Date toDate, String type) {

    return [SELECT Id, Name, Project__c, Project__r.Name,TaskType__c, Description__c, Hours__c, Minutes__c, CreatedDate, LastModifiedDate, isApproved__c, Date__c, External_User__c
            FROM Report__c
            WHERE Date__c <= :toDate AND Date__c>=:fromDate AND External_User__c = :userId and Project__r.Name ='Social package' and TaskType__c=:type];
    }


    @AuraEnabled
    public static Report__c getReportById(Id reportId) {
    return [SELECT Id, Name, Project__c, TaskType__c, Description__c, Hours__c, Minutes__c, CreatedDate, LastModifiedDate, isApproved__c, Date__c
            FROM Report__c
            WHERE Id=:reportId];
    }

    @AuraEnabled
    public static void createReport(String dateISO, String projectId, String task, String description, Integer minutesSpent, Integer hoursSpent, Id userId) {
        Date reportDate = Date.valueOf(dateISO);
        Report__c report = new Report__c(
            Date__c = reportDate,
            Project__c = projectId,
            TaskType__c = task,
            Description__c = description,
            Minutes__c = minutesSpent,
            Hours__c = hoursSpent,
            External_User__c = userId
        );
        insert report;
    }


    public static Report__c createReportWithoutInsert(Date reportDate, String projectId, String task, String description, Integer minutesSpent, Integer hoursSpent, Id userId) {
        Report__c report = new Report__c(
            Date__c = reportDate,
            Project__c = projectId,
            TaskType__c = task,
            Description__c = description,
            Minutes__c = minutesSpent,
            Hours__c = hoursSpent,
            External_User__c = userId,
            IsApproved__c = true

        );
        return report;
    }


    @AuraEnabled
    public static void updateReport(String reportId, String projectId, String task, String description, Integer minutesSpent, Integer hoursSpent) {
        Report__c report = [
            SELECT Id, Project__c, TaskType__c, Description__c, Hours__c, Minutes__c
            FROM Report__c
            WHERE Id = :reportId
            LIMIT 1
        ];

        report.Project__c = projectId;
        report.TaskType__c = task;
        report.Description__c = description;
        report.Minutes__c = minutesSpent;
        report.Hours__c = hoursSpent;

        update report;
    }

    @AuraEnabled
    public static void deleteReport(Id reportId) {
        Report__c report = [
            SELECT Id FROM Report__c WHERE Id = :reportId LIMIT 1
        ];
        delete report;
    }




    @AuraEnabled
    public static void updateReportStatus(Id reportId, Boolean value) {
        Report__c report = [
            SELECT Id, Project__c, TaskType__c, Description__c, Hours__c, Minutes__c, IsApproved__c
            FROM Report__c
            WHERE Id =:reportId
            LIMIT 1
        ];

        report.IsApproved__c = value;
        update report;
    }


    @AuraEnabled
    public static void updateReportsStatusesByWeek(String startDateISO, String endDateISO, Boolean value) {
        List<Report__c> reports = [
            SELECT Id, Project__c, TaskType__c, Description__c, Hours__c, Minutes__c, IsApproved__c
            FROM Report__c
            WHERE Date__c >= :Date.valueOf(startDateISO)
            AND Date__c <= :Date.valueOf(endDateISO)
        ];
        for (Report__c report : reports) {
            report.IsApproved__c = value;
        }
        update reports;
   
    }
}