force-app/main/default/objects/External_User__c/External_User__c.object-meta.xml
<CustomObject>
    <label>External User</label>
    <nameField>
        <label>External User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_User__c/fields/EnglishLevel__c.field-meta.xml
<CustomField>
    <fullName>EnglishLevel__c</fullName>
    <label>EnglishLevel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Pre-Intermediate</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Upper-Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_User__c/fields/FirstWorkingDate__c.field-meta.xml
<CustomField>
    <fullName>FirstWorkingDate__c</fullName>
    <label>FirstWorkingDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/HR__c.field-meta.xml
<CustomField>
    <fullName>HR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HR</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You want to assign a user which is not HR</errorMessage>
        <filterItems>
            <field>External_User__c.IsHR__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>External_User__c</referenceTo>
    <relationshipLabel>External Users (External User)</relationshipLabel>
    <relationshipName>External_Users1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/IsHR__c.field-meta.xml
<CustomField>
    <fullName>IsHR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsHR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/IsManager__c.field-meta.xml
<CustomField>
    <fullName>IsManager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsManager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trainee</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Middle</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_User__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You want to assign user which is not a manager</errorMessage>
        <filterItems>
            <field>External_User__c.IsManager__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>External_User__c</referenceTo>
    <relationshipLabel>External Users</relationshipLabel>
    <relationshipName>External_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/Used_Budget__c.field-meta.xml
<CustomField>
    <fullName>Used_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/Used_Days_Off__c.field-meta.xml
<CustomField>
    <fullName>Used_Days_Off__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Days Off</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/Used_Illnesses__c.field-meta.xml
<CustomField>
    <fullName>Used_Illnesses__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Illnesses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/External_User__c/fields/Used_Vacations__c.field-meta.xml
<CustomField>
    <fullName>Used_Vacations__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Vacations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExternalUsersController.cls
public without sharing class ExternalUsersController {



    @AuraEnabled
    public static List<External_User__c> getAllExternalUsers() {
        return [SELECT Id, Name, Manager__c, Role__c FROM External_User__c];
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<External_User__c> getAllExternalUsersByManager(Id managerId) {
        return [SELECT Id, Name, Manager__c, Role__c FROM External_User__c where Manager__c = :managerId];
    }    

    @AuraEnabled
    public static External_User__c getExternalUserById(Id userId){
        External_User__c user = [SELECT Id,Name, Used_Budget__c, Used_Days_Off__c, Used_Illnesses__c, Used_Vacations__c, FirstWorkingDate__c, HR__r.Name, EnglishLevel__c, IsHR__c, Manager__r.Name, Manager__c, HR__c, IsManager__c, Role__c, Level__c, Email__c, Phone__c   FROM External_User__c WHERE Id = :userId LIMIT 1];
        return user;
    }

    public static Map<Id, External_User__c> getExternalUsersByIdBatch(Set<Id> userIds){
        Map<Id, External_User__c> usersMap = new Map<Id, External_User__c>([SELECT Id,Name, Used_Budget__c, Used_Days_Off__c, Used_Illnesses__c, Used_Vacations__c, FirstWorkingDate__c, HR__r.Name, EnglishLevel__c, IsHR__c, Manager__r.Name, Manager__c, HR__c, IsManager__c, Role__c, Level__c, Email__c, Phone__c   FROM External_User__c WHERE Id in :userIds]);
        return usersMap;
    }
      

    @AuraEnabled(cacheable=true)
    public static List<External_User__c> getUsersByFilters(Integer pageSize, Integer pageNumber, String nameFilter, String roleFilter, String leadFilter, String clientFilter) {
        String baseQuery = 'SELECT Id, Name, Email__c, Role__c, Manager__r.Name, HR__r.Name FROM External_User__c WHERE Email__c != null';
        System.debug('hello');
        if (String.isNotBlank(nameFilter)) {
            baseQuery += ' AND Name LIKE \'%' + String.escapeSingleQuotes(nameFilter) + '%\'';
        }
        if (String.isNotBlank(roleFilter)) {
            baseQuery += ' AND Role__c = \'' + String.escapeSingleQuotes(roleFilter) + '\'';
        }
        if (String.isNotBlank(leadFilter)) {
            baseQuery += ' AND Manager__c = \'' + String.escapeSingleQuotes(leadFilter) + '\'';
        }

        Integer offsetSize = Integer.valueOf(pageSize) * (Integer.valueOf(pageNumber)-1);
   

        baseQuery += ' ORDER BY Name LIMIT :pageSize OFFSET :offsetSize';
        System.debug(baseQuery);
        return Database.query(baseQuery);
    }

    @AuraEnabled(cacheable=true)
    public static Integer getTotalCount(String nameFilter, String roleFilter, String leadFilter, String clientFilter) {
        String baseQuery = 'SELECT COUNT() FROM External_User__c WHERE Email__c != null';

        if (String.isNotBlank(nameFilter)) {
            baseQuery += ' AND Name LIKE \'%' + String.escapeSingleQuotes(nameFilter) + '%\'';
        }
        if (String.isNotBlank(roleFilter)) {
            baseQuery += ' AND Role__c = \'' + String.escapeSingleQuotes(roleFilter) + '\'';
        }
        if (String.isNotBlank(leadFilter)) {
            baseQuery += ' AND Manager__c = \'' + String.escapeSingleQuotes(leadFilter) + '\'';
        }

        return (Integer)Database.countQuery(baseQuery);
    }


    @AuraEnabled
    public static List<External_User__c> getManagers() {
        return [
            SELECT Id, Name 
            FROM External_User__c 
            WHERE IsManager__c = TRUE 
            ORDER BY Name
        ];
    }

    @AuraEnabled
    public static List<External_User__c> getAllHRs() {
        return [SELECT Id, Name FROM External_User__c WHERE IsHR__c = TRUE ORDER BY Name];
    }

    @AuraEnabled
    public static void saveUser(External_User__c userRecord) {
        upsert userRecord;
    }


}